# Generated by Django 4.0.3 on 2023-06-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipy',
            fields=[
                ('nazwa_ekipy', models.CharField(default='', max_length=200)),
                ('sesje_ses_number', models.CharField(default='', max_length=200)),
                ('ekipy_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gry',
            fields=[
                ('nr_gry', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('nazwa_gry', models.CharField(default='', max_length=200)),
                ('czas_trwania', models.CharField(default='', max_length=200)),
                ('lokalizacja', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hosty',
            fields=[
                ('h_nick', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('sesje_ses_number', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Punktowi',
            fields=[
                ('p_nick', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('ses_num', models.CharField(default='', max_length=200)),
                ('sesje_ses_number', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='gracze',
            name='ses',
        ),
        migrations.AlterField(
            model_name='gracze',
            name='g_nick',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gracze',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sesje',
            name='game_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sesje',
            name='ses_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Zadania',
            fields=[
                ('id_zadania', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('opis_zadania', models.CharField(default='', max_length=200)),
                ('nazwa_zadania', models.CharField(default='', max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gry_nr_gry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra.gry')),
            ],
        ),
        migrations.AddField(
            model_name='gracze',
            name='ekipy_ekipy_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gra.ekipy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesje',
            name='gry_nr_gry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gra.gry'),
        ),
    ]
